"use client";
import { useEffect,useRef,useState } from "react";
import { Camera,ShieldCheck,Square,Play,Loader2 } from "lucide-react";
import { toast } from "sonner";
import type { Api } from "./tutor-app";
import type { ProctorEvent,State } from "@/lib/contracts";
const names:Record<string,string>={tab_hidden:"Уход с вкладки",camera_on:"Камера включена",camera_off:"Камера отключена",camera_error:"Наблюдение недоступно",no_face:"Лицо не найдено",multiple_faces:"Несколько лиц"};
export function ProctorPanel({api,refresh,sessions,events,examSessionId}:{api:Api;refresh:()=>Promise<void>;sessions:State["sessions"];events:ProctorEvent[];examSessionId?:string}){
 const [active,setActive]=useState<string|null>(examSessionId||null),[camera,setCamera]=useState(false),[busy,setBusy]=useState(false),[message,setMessage]=useState("Камера выключена"),[selected,setSelected]=useState<string|null>(examSessionId||null);
 const video=useRef<HTMLVideoElement>(null),stream=useRef<MediaStream|null>(null),timer=useRef<ReturnType<typeof setInterval>|null>(null),detector=useRef<import("@mediapipe/tasks-vision").FaceDetector|null>(null),mounted=useRef(true),activeRef=useRef<string|null>(examSessionId||null),generation=useRef(0);
 const pending=useRef<Promise<unknown>[]>([]);
 const log=async(kind:string,detail:string)=>{const session=activeRef.current;if(!session)return;const promise=api(`exam-sessions/${session}/events`,{kind,detail}).then(()=>refresh()).catch((e:Error)=>toast.error(`Событие не сохранено: ${e.message}`));pending.current.push(promise);await promise;pending.current=pending.current.filter(p=>p!==promise);};
 function stopCamera(){generation.current++;if(timer.current)clearInterval(timer.current);timer.current=null;stream.current?.getTracks().forEach(t=>t.stop());stream.current=null;detector.current?.close();detector.current=null;if(video.current)video.current.srcObject=null;if(mounted.current){setCamera(false);setMessage("Камера выключена");}}
 useEffect(()=>{mounted.current=true;return()=>{mounted.current=false;const session=activeRef.current;activeRef.current=null;stopCamera();if(session&&!examSessionId)void api(`exam-sessions/${session}/end`,{}).catch(()=>{});};},[]);
 useEffect(()=>{if(!active)return;const handler=()=>{if(document.hidden)void log("tab_hidden","Страница перестала быть видимой. Причина не установлена.");};document.addEventListener("visibilitychange",handler);return()=>document.removeEventListener("visibilitychange",handler);},[active]);
 async function start(){setBusy(true);try{const session=await api("exam-sessions",{});activeRef.current=session.id;setActive(session.id);setSelected(session.id);await refresh();}catch(e){toast.error((e as Error).message);}finally{setBusy(false);}}
 async function end(){setBusy(true);try{if(stream.current)await log("camera_off","Наблюдение завершено пользователем");stopCamera();await Promise.all(pending.current);await api(`exam-sessions/${active}/end`,{});activeRef.current=null;setActive(null);await refresh();}catch(e){toast.error((e as Error).message);}finally{setBusy(false);}}
 async function enableCamera(){setBusy(true);setMessage("Загружаем локальную модель…");const token=++generation.current;let acquired:MediaStream|null=null;let created:import("@mediapipe/tasks-vision").FaceDetector|null=null;try{const {FilesetResolver,FaceDetector}=await import("@mediapipe/tasks-vision");const vision=await FilesetResolver.forVisionTasks("/mediapipe/wasm");created=await FaceDetector.createFromOptions(vision,{baseOptions:{modelAssetPath:"/mediapipe/blaze_face_short_range.tflite"},runningMode:"VIDEO",minDetectionConfidence:0.65});if(!mounted.current||generation.current!==token){created.close();return;}acquired=await navigator.mediaDevices.getUserMedia({video:{width:640,height:480},audio:false});if(!mounted.current||generation.current!==token){acquired.getTracks().forEach(t=>t.stop());created.close();return;}stream.current=acquired;detector.current=created;video.current!.srcObject=acquired;await video.current!.play();if(!mounted.current||generation.current!==token){acquired.getTracks().forEach(t=>t.stop());return;}setCamera(true);setMessage("Локальный анализ активен");await log("camera_on","Кадры анализируются на устройстве и не сохраняются");if(!mounted.current||generation.current!==token)return;let streak=0,lastKind="",lastAt=0;timer.current=setInterval(()=>{if(!video.current||!detector.current||video.current.readyState<2||document.hidden)return;try{const count=detector.current.detectForVideo(video.current,performance.now()).detections.length;const kind=count===0?"no_face":count>1?"multiple_faces":"";if(!kind){streak=0;lastKind="";return;}streak=kind===lastKind?streak+1:1;lastKind=kind;if(streak>=6&&Date.now()-lastAt>15000){lastAt=Date.now();void log(kind,`Устойчивый сигнал около 3 секунд. Требует проверки преподавателем.`);}}catch{stopCamera();setMessage("Ошибка модели: наблюдение остановлено");void log("camera_error","Ошибка локального детектора");}},500);acquired.getVideoTracks()[0].onended=()=>{stopCamera();void log("camera_off","Доступ к камере прекращён");};}catch(e){acquired?.getTracks().forEach(t=>t.stop());created?.close();stream.current=null;detector.current=null;if(mounted.current){setCamera(false);setMessage("Камера или модель недоступна. Запись не ведётся.");await log("camera_error",e instanceof Error?e.name:"Ошибка камеры");}}finally{if(mounted.current)setBusy(false);}}
 const displayed=selected||sessions[0]?.id,session=sessions.find(s=>s.id===displayed),filtered=events.filter(e=>e.sessionId===displayed);
 return <><div className="page-heading"><div><p className="eyebrow">НАБЛЮДЕНИЕ</p><h2>События во время экзамена</h2><p className="muted">Сигналы помогают преподавателю разобрать спорную ситуацию.</p></div><span className="pill">Без автоматических санкций</span></div><div className="exam-layout"><section className="panel"><div className="section-heading"><h2>Камера</h2><ShieldCheck className="text-primary"/></div><p className="muted">Сохраняются время и тип событий. Камера включается отдельно; кадры обрабатываются на устройстве и не записываются.</p><div className="camera-frame"><video ref={video} muted playsInline className={camera?"":"hidden"}/>{!camera&&<div><Camera size={36}/><p>{message}</p></div>}{camera&&<span className="camera-label">{message}</span>}</div><div className="button-row">{!active?<button disabled={busy} className="primary" onClick={start}><Play size={17}/>Начать сессию</button>:<><button disabled={busy} className="secondary" onClick={camera?async()=>{stopCamera();await log("camera_off","Пользователь выключил камеру");}:enableCamera}>{busy?<Loader2 size={17} className="animate-spin"/>:<Camera size={17}/>} {camera?"Выключить камеру":"Разрешить камеру и AI-анализ"}</button>{!examSessionId&&<button disabled={busy} className="danger" onClick={end}><Square size={16}/>Завершить</button>}</>}</div><p className="footnote">Сигналы не доказывают списывание и не меняют оценку автоматически.</p></section><section className="panel"><div className="section-heading"><h2>Журнал событий</h2><button className="secondary" onClick={refresh}>Обновить</button></div>{sessions.length>0&&<div className="session-list">{sessions.slice(0,5).map((s,i)=><button key={s.id} onClick={()=>setSelected(s.id)} className={displayed===s.id?"pill":"secondary"}>Сессия {sessions.length-i} · {s.endedAt?"завершена":"открыта"}</button>)}</div>}<p className="muted text-sm">{session?new Date(session.startedAt).toLocaleString("ru-RU"):"Сессий пока нет"}</p><div className="event-list">{filtered.map(e=><div className="event" key={e.id}><span className="event-time">{new Date(e.createdAt).toLocaleTimeString("ru-RU")}</span><div><h3>{names[e.kind]||e.kind}</h3><p>{e.detail}</p></div></div>)}{!filtered.length&&<div className="empty-panel"><ShieldCheck size={28}/><p>Событий пока нет</p><small>Отсутствие событий не доказывает отсутствие нарушений.</small></div>}</div></section></div></>;
}
