import { database, HttpError, id, now } from "@/lib/server";

export type User = { id:string; email:string; name:string; role:"teacher"|"student" };
const encoder = new TextEncoder();
const hex = (bytes:Uint8Array) => [...bytes].map(v=>v.toString(16).padStart(2,"0")).join("");
const bytes = (length:number) => crypto.getRandomValues(new Uint8Array(length));
async function digest(value:string){return hex(new Uint8Array(await crypto.subtle.digest("SHA-256",encoder.encode(value))));}
export async function hashPassword(password:string,salt=hex(bytes(16))){const key=await crypto.subtle.importKey("raw",encoder.encode(password),"PBKDF2",false,["deriveBits"]);const bits=await crypto.subtle.deriveBits({name:"PBKDF2",hash:"SHA-256",salt:encoder.encode(salt),iterations:210000},key,256);return `pbkdf2:210000:${salt}:${hex(new Uint8Array(bits))}`;}
export async function verifyPassword(password:string,stored:string){const parts=stored.split(":");if(parts.length!==4||parts[0]!=="pbkdf2")return false;const computed=await hashPassword(password,parts[2]);const a=encoder.encode(computed),b=encoder.encode(stored);if(a.length!==b.length)return false;let difference=0;for(let i=0;i<a.length;i++)difference|=a[i]^b[i];return difference===0;}
export async function createSession(userId:string,request:Request){const token=hex(bytes(32));const expiresAt=new Date(Date.now()+30*86400000).toISOString();await database().prepare("INSERT INTO auth_sessions (tokenHash,userId,expiresAt) VALUES (?,?,?)").bind(await digest(token),userId,expiresAt).run();return cookie(token,request,30*86400);}
export function cookie(token:string,request:Request,maxAge:number){const secure=new URL(request.url).protocol==="https:"?"; Secure":"";return `tutorlab_session=${token}; HttpOnly; SameSite=Lax; Path=/; Max-Age=${maxAge}${secure}`;}
export async function getUser(request:Request):Promise<User|null>{const token=request.headers.get("cookie")?.match(/(?:^|;\s*)tutorlab_session=([a-f0-9]{64})(?:;|$)/)?.[1];if(!token)return null;const user=await database().prepare("SELECT u.id,u.email,u.name,u.role FROM auth_sessions s JOIN users u ON u.id=s.userId WHERE s.tokenHash=? AND s.expiresAt>?").bind(await digest(token),now()).first<User>();return user||null;}
export async function requireUser(request:Request){const user=await getUser(request);if(!user)throw new HttpError(401,"Войдите в аккаунт");return user;}
export function requireTeacher(user:User){if(user.role!=="teacher")throw new HttpError(403,"Действие доступно преподавателю");}
export async function removeSession(request:Request){const token=request.headers.get("cookie")?.match(/(?:^|;\s*)tutorlab_session=([a-f0-9]{64})(?:;|$)/)?.[1];if(token)await database().prepare("DELETE FROM auth_sessions WHERE tokenHash=?").bind(await digest(token)).run();return cookie("",request,0);}
export function checkOrigin(request:Request){if(["GET","HEAD","OPTIONS"].includes(request.method))return;const origin=request.headers.get("origin"),url=new URL(request.url);if(origin!==url.origin)throw new HttpError(403,"Недопустимый источник запроса");}
export async function canAccessCourse(courseId:string,user:User){const course=await database().prepare("SELECT id,teacherId FROM courses WHERE id=?").bind(courseId).first<{id:string;teacherId:string|null}>();if(!course)throw new HttpError(404,"Курс не найден");if(course.teacherId===user.id)return true;const enrolled=await database().prepare("SELECT 1 FROM enrollments WHERE courseId=? AND userId=?").bind(courseId,user.id).first();if(!enrolled)throw new HttpError(403,"Нет доступа к курсу");return false;}
export async function ownCourse(courseId:string,user:User){requireTeacher(user);const owner=await canAccessCourse(courseId,user);if(!owner)throw new HttpError(403,"Это курс другого преподавателя");}
export async function submissionAccess(submissionId:string,user:User){const submission=await database().prepare("SELECT s.*,t.courseId,c.teacherId FROM submissions s JOIN tasks t ON t.id=s.taskId JOIN courses c ON c.id=t.courseId WHERE s.id=?").bind(submissionId).first<Record<string,unknown>>();if(!submission)throw new HttpError(404,"Работа не найдена");if(submission.studentId!==user.id&&submission.teacherId!==user.id)throw new HttpError(403,"Нет доступа к работе");return submission;}
export const newId=id;
