import { z } from "zod";
export const courseInput = z.object({ title:z.string().trim().min(2).max(160), subject:z.enum(["math","physics","code"]), description:z.string().max(2000).default("") });
export const taskInput = z.object({ courseId:z.string().min(1), title:z.string().trim().min(2).max(160), statement:z.string().trim().min(5).max(20000), kind:z.enum(["numeric","written","code"]), maxScore:z.number().int().min(1).max(100), expected:z.string().max(12000).default(""), tolerance:z.number().finite().min(0).max(1000).default(0.001), rubric:z.string().max(12000).default(""), tests:z.array(z.object({input:z.string().max(5000),output:z.string().max(5000),hidden:z.boolean()})).max(20).default([]) }).superRefine((v,c)=>{ if(v.kind==="numeric" && parseNumeric(v.expected)===null)c.addIssue({code:"custom",message:"Укажите числовой эталон",path:["expected"]}); if(v.kind==="written" && (!v.expected.trim()||!v.rubric.trim()))c.addIssue({code:"custom",message:"Добавьте эталон и критерии",path:["rubric"]}); if(v.kind==="code" && !v.tests.length)c.addIssue({code:"custom",message:"Добавьте хотя бы один тест",path:["tests"]}); });
export const reviewSchema = z.object({ score:z.number().finite().min(0), summary:z.string().min(1).max(6000), strengths:z.array(z.string().max(1000)).max(12), improvements:z.array(z.string().max(1000)).max(12) });
export function parseNumeric(value:string):number|null { const normalized=value.trim().replace(",","."); if(!/^[+-]?(?:\d+(?:\.\d*)?|\.\d+)(?:e[+-]?\d+)?$/i.test(normalized))return null; const n=Number(normalized); return Number.isFinite(n)?n:null; }
export function numericReview(answer:string,expected:string,tolerance:number,maxScore:number) { const a=parseNumeric(answer), e=parseNumeric(expected); if(e===null)throw new Error("Некорректный эталон"); const correct=a!==null && Math.abs(a-e)<=tolerance+Number.EPSILON*Math.max(1,Math.abs(e)); return {score:correct?maxScore:0,summary:a===null?"Ответ не распознан как число. Нужна ручная проверка.":correct?"Числовой ответ совпадает с эталоном в пределах допуска.":"Числовой ответ не совпадает с эталоном.",strengths:correct?["Верный итоговый ответ"]:[],improvements:correct?[]:["Проверьте вычисления и единицы из условия"],source:"numeric"}; }
export type Course = z.infer<typeof courseInput> & {id:string;createdAt:string;inviteCode?:string};
export type Task = Omit<z.infer<typeof taskInput>,"expected"|"rubric"|"tolerance"> & {id:string;expected?:string;rubric?:string;tolerance?:number;createdAt:string};
export type Review = z.infer<typeof reviewSchema> & {source:string;model?:string};
export type Submission = {id:string;taskId:string;sessionId?:string|null;studentName?:string;answer:string;language:string;status:string;review:Review|null;score:number|null;comment:string|null;createdAt:string};
export type Lesson = {id:string;courseId:string;title:string;body:string;fileKey:string|null;fileName:string|null;mime:string|null};
export type ProctorEvent = {id:string;sessionId:string;kind:string;detail:string;createdAt:string};
export type Exam = {id:string;courseId:string;title:string;durationMinutes:number;taskIds:string[];createdAt:string};
export type User = {id:string;email:string;name:string;role:"teacher"|"student"};
export type State = {user?:User;courses:Course[];tasks:Task[];lessons:Lesson[];exams:Exam[];submissions:Submission[];sessions:{id:string;examId:string|null;studentName?:string;startedAt:string;endsAt:string|null;endedAt:string|null}[];events:ProctorEvent[];services:{ai:boolean;judge:boolean;model:string;demo:boolean}};
