const origin='http://127.0.0.1:8787';
const stamp=Date.now();
function client(){let token='';return async(path,body,method)=>{await new Promise(r=>setTimeout(r,150));const headers={Origin:origin};if(token)headers['x-tutorlab-session']=token;if(body!==undefined&&!(body instanceof Uint8Array))headers['Content-Type']='application/json';if(body instanceof Uint8Array)headers['Content-Type']='video/mp4';let response;for(let attempt=0;attempt<4;attempt++){response=await fetch(origin+'/api/'+path,{method:method||(body===undefined?'GET':'POST'),headers,body:body===undefined?undefined:body instanceof Uint8Array?body:JSON.stringify(body)});if(response.status!==503||!response.headers.has('retry-after'))break;await new Promise(r=>setTimeout(r,500));}let value;if(response.headers.get('content-type')?.includes('application/json'))value=await response.json();else value=await response.arrayBuffer();if(value?.sessionToken)token=value.sessionToken;return {status:response.status,value,headers:response.headers};};}
function ok(result,status,label){if(result.status!==status)throw new Error(`${label}: expected ${status}, got ${result.status}: ${JSON.stringify(result.value)}; headers: ${JSON.stringify([...result.headers])}`);return result.value;}
const teacher=client(),student=client(),stranger=client();
ok(await teacher('auth/register',{name:'Teacher',email:`teacher-${stamp}@example.test`,password:'SomeLongPassword1',role:'teacher'}),201,'teacher registration');
ok(await student('auth/register',{name:'Student',email:`student-${stamp}@example.test`,password:'SomeLongPassword1',role:'student'}),201,'student registration');
ok(await stranger('auth/register',{name:'Other',email:`other-${stamp}@example.test`,password:'SomeLongPassword1',role:'student'}),201,'stranger registration');
const course=ok(await teacher('courses',{title:'Algebra',subject:'math',description:'Test'}),201,'create course');
const task=ok(await teacher('tasks',{courseId:course.id,title:'Two plus two',statement:'Find 2 + 2.',kind:'numeric',maxScore:10,expected:'4',tolerance:0,rubric:'',tests:[]}),201,'create task');
const exam=ok(await teacher('exams',{courseId:course.id,title:'Algebra exam',durationMinutes:5,taskIds:[task.id]}),201,'create exam');
const emptyStudentState=ok(await student('state'),200,'student empty state');
if(emptyStudentState.user?.email!==`student-${stamp}@example.test`)throw new Error('empty state lost authenticated user');
ok(await stranger('courses/join',{code:'WRONGCODE'}),404,'invalid code');
ok(await student('courses/join',{code:course.inviteCode}),200,'join course');
const studentState=ok(await student('state'),200,'student state');
if(studentState.courses.length!==1||studentState.tasks.length!==0||studentState.courses[0].inviteCode!==undefined)throw new Error('student data scope failed');
ok(await stranger('submissions',{taskId:task.id,answer:'4',language:'python'}),403,'stranger submission');
ok(await student('submissions',{taskId:task.id,answer:'4',language:'python'}),403,'exam task outside attempt');
const attempt=ok(await student(`exams/${exam.id}/start`,{}),201,'start exam');
const examState=ok(await student('state'),200,'active exam state');
if(!examState.tasks.some(t=>t.id===task.id&&t.expected===undefined))throw new Error('exam task not released safely');
const submission=ok(await student('submissions',{taskId:task.id,answer:'4',language:'python',sessionId:attempt.id}),201,'student submission');
ok(await student('submissions',{taskId:task.id,answer:'4',language:'python',sessionId:attempt.id}),409,'duplicate exam answer');
ok(await student(`exam-sessions/${attempt.id}/events`,{kind:'tab_hidden',detail:'Test event'}),200,'proctor event');
ok(await student(`exams/${exam.id}/finish`,{}),200,'finish exam');
ok(await student('submissions',{taskId:task.id,answer:'4',language:'python',sessionId:attempt.id}),409,'late answer');
ok(await stranger(`submissions/${submission.id}/grade`,{score:10,comment:'hacked'}),403,'stranger grade');
ok(await student(`submissions/${submission.id}/grade`,{score:10,comment:'hacked'}),403,'student grade');
ok(await teacher(`submissions/${submission.id}/grade`,{score:10,comment:'Well done'}),200,'teacher grade');
const studentResult=ok(await student('state'),200,'student graded state');
if(studentResult.submissions[0].score!==10)throw new Error('grade not visible');
const video=ok(await teacher('videos/init',{courseId:course.id,title:'Lesson video',body:'',fileName:'example.mp4',mime:'video/mp4',size:8}),201,'video init');
ok(await teacher(`videos/${video.id}/upload`,new Uint8Array([0,0,0,4,102,116,121,112]),'PUT'),200,'video upload');
const videoState=ok(await student('state'),200,'video state');
const fileKey=videoState.lessons.find(l=>l.id===video.id)?.fileKey;
if(!fileKey)throw new Error('video missing from student state');
ok(await student(`files/${fileKey}`),200,'student video access');
ok(await stranger(`files/${fileKey}`),403,'stranger video access');
ok(await teacher('auth/logout',{}),200,'logout');
console.log('Product check passed: auth, enrollment, isolation, submission, grade, video upload/access, logout');
